import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-sandbox'] });
const ctx = await b.newContext({ viewport:{width:390,height:844}, isMobile:true, hasTouch:true });
for (const p of ['**://*.googleapis.com/**','**://*.firebaseio.com/**','**://*.firebaseapp.com/**','**://*.gstatic.com/**']) await ctx.route(p, r=>r.abort());
const page = await ctx.newPage();
const cdp = await ctx.newCDPSession(page);
await cdp.send('Network.enable');
// 4G lenta: 1.6 Mbps bajada, 150 ms de latencia
await cdp.send('Network.emulateNetworkConditions', { offline:false, downloadThroughput: 1.6*1024*1024/8, uploadThroughput: 750*1024/8, latency: 150 });
const recursos = [];
page.on('response', async r => { const u=r.url(); if(/\.(js|css)$/.test(u)) { const h = await r.allHeaders(); recursos.push({ f: u.split('/').pop(), kb: Math.round((+h['content-length']||0)/1024) }); } });
const t0 = Date.now();
await page.goto('http://localhost:4173/index.html?c='+encodeURIComponent(JSON.stringify({evento:'boda',pax:120})), { waitUntil:'domcontentloaded' });
await page.locator('.item-row').first().waitFor({ timeout: 30000 });
const interactiva = Date.now()-t0;
await page.waitForTimeout(4000);
console.log('tiempo hasta ver la checklist:', interactiva, 'ms');
console.log('recursos:', JSON.stringify(recursos));
console.log('total JS+CSS:', recursos.reduce((a,r)=>a+r.kb,0), 'KB');
await b.close();
